[project]
name = "radiomics-lesions"
version = "0.1.0"
authors = []
requires-python = ">=3.12,<3.14"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "torch>=2.9.0",
    "lightning>=2.4.0",
    "torchmetrics>=1.4.1",
    "rationai-mlkit",
    "nibabel>=5.4.2",
    "scipy>=1.15",
    "numpy>=2.0",
    "huggingface-hub>=0.34",
    "omegaconf>=2.3",
    "hydra-core>=1.3",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = ["mypy", "ruff"]


[project.optional-dependencies]
job = ["rationai-kube-jobs"]

[tool.uv.sources]
rationai-kube-jobs = { git = "ssh://git@gitlab.ics.muni.cz/rationai/infrastructure/kube-jobs" }
rationai-mlkit = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/mlkit.git" }
