defaults:
  - hydra: default
  - logger: mlflow
  - _self_

seed: 0
mode: [fit, test]
checkpoint:
  test: best

trainer:
  precision: 16-mixed
  gradient_clip_val: 0.1
  enable_checkpointing: true
  check_val_every_n_epoch: 5
  callbacks:
    model_checkpoint:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      save_last: true
      monitor: validation/macro_f1
      mode: max
    finetune:
      _target_: lightning.pytorch.callbacks.BackboneFinetuning
      unfreeze_backbone_at_epoch: 30
      backbone_initial_ratio_lr: 0.1

data:
  _target_: ml.data.DataModule
  manifest: /mnt/projects/radiomics/isotropic_crops_1mm/manifest.json
  root: /mnt/projects/radiomics/isotropic_crops_1mm # override when moving the preprocessed dataset
  batch_size: 2 # lesions, not scans
  num_workers: 4

model:
  _target_: ml.meta_arch.MetaArch

metadata:
  experiment_name: Radiomics Lesions
  run_name: Training
  description: ""
